title: <p align="center"> Javvaji Gokul </p>
logo: /assets/img/logo.png

description:
  <br>   
I'm Senior Technical Lead who handles Java Full Stack Development Team.
  <br>
  </p>



theme: jekyll-theme-minimal
